  - name: Install dependencies
    apt:
      name: 
       - ca-certificates 
       - curl 
       - gnupg 
       - lsb-release
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    become: true

  - name: Add docker repository to apt
    apt_repository:
      filename: docker 
      #repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bullseye stable
      repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
      state: present
    become: true

  - name: Install docker engine
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      state: present
      update_cache: true
    become: true

  #- name: Test docker
  #  command: docker info
  #  become: true
  
  - name: Install docker-compose
    import_tasks: compose.yml
    #become: true
    tags: docker_compose



  
